// Clip-list export. Two formats, both pure functions of the
// bookmarks array + source filename + a time formatter:
//
//   exportJson      — re-importable, faithful to in-app state
//   exportFfmpegSh  — copy-paste-into-a-real-terminal recipe; one
//                     `ffmpeg -ss X -t Y` per bookmark, -c copy for
//                     speed (snaps to keyframes, no re-encode).
//
// The host calls these from a modal whose UI lives in index.html.

export function exportJson(bookmarks, fileName) {
    // Order the same way they appear in the UI (sort by start).
    const rows = [...bookmarks].sort((a, b) => a.start - b.start);
    return JSON.stringify({
        source_file: fileName || null,
        exported_at: new Date().toISOString(),
        bookmarks: rows.map(c => ({
            label: c.label || '',
            start_seconds: c.start,
            end_seconds: c.end,
            duration_seconds: c.end - c.start,
            color: c.color || null,
        })),
    }, null, 2);
}

// Shell-safe quoting for filenames + labels. Wraps the value in
// single quotes and escapes any embedded single quotes by closing
// the quote, escaping, and reopening. Standard POSIX idiom:
// 'don'\''t' = don't.
export function shellQuote(s) {
    return `'${String(s).replace(/'/g, `'\\''`)}'`;
}

export function exportFfmpegSh(bookmarks, fileName, formatTimecode) {
    const rows = [...bookmarks].sort((a, b) => a.start - b.start);
    const src = fileName || 'input.mp4';
    const baseStem = src.replace(/\.[^.]+$/, '');
    const lines = [
        '#!/usr/bin/env bash',
        '# Generated by ContextClipper.',
        `# Source: ${src.replace(/[\r\n]+/g, ' ')}`,
        '# Run from the directory containing the source video.',
        '# -c copy makes cuts at the nearest keyframes (no re-encode).',
        'set -eu',
        '',
    ];
    rows.forEach((c, i) => {
        const safeLabel = (c.label || `clip-${i + 1}`)
            .replace(/[^A-Za-z0-9._-]+/g, '_')
            .replace(/^_+|_+$/g, '') || `clip-${i + 1}`;
        const out = `${baseStem}.${safeLabel}.mp4`;
        const dur = c.end - c.start;
        // Strip newlines so a multi-line label can't break out of the
        // comment into an executable line of the generated script.
        const commentLabel = (c.label || `Clip ${i + 1}`).replace(/[\r\n]+/g, ' ');
        lines.push(`# ${commentLabel} — ${formatTimecode(c.start)} → ${formatTimecode(c.end)} (${dur.toFixed(2)}s)`);
        lines.push(
            `ffmpeg -y -ss ${c.start.toFixed(3)} -i ${shellQuote(src)} ` +
            `-t ${dur.toFixed(3)} -c copy ${shellQuote(out)}`
        );
        lines.push('');
    });
    return lines.join('\n');
}

// Filename suggestion for the Download button — `<stem>.bookmarks.json`
// or `<stem>.clips.sh` depending on the chosen format.
export function exportFilename(fileName, format) {
    const stem = (fileName || 'clips').replace(/\.[^.]+$/, '');
    return format === 'json' ? `${stem}.bookmarks.json` : `${stem}.clips.sh`;
}
